const os = require ('node:os')
console.log('informacion del sistema operativo')
console.log('nombre del sistema operativo',os.platform())
console.log('version del sistema operativo', os.release())
console.log('arquitectura',os.arch())
console.log('CPUS', os.cpus())
console.log ('memorialibre', os.freemem())
